### ISSUE TITLE
Sometimes the context menu fails to appear

### ISSUE THREAD

**Issue by electr0sheep** [kalilistic/Dalamud.ContextMenu#6]
I'm not sure what all conditions reproduce this. I know I've received reports of the context menu being _very_ temperamental. Possibly it depends on hardware, but I've never encountered problems unless I'm trying to cause problems. Gonna try to link my own issue which contains a gif.

https://github.com/electr0sheep/ItemVendorLocation/issues/43

**Comment by electr0sheep** [comment]
Er, I just realized that the Allagan Tools option is still there. Now I'm wondering if this is actually my problem.

**Comment by kalilistic** [comment]
I'll mark it as a question for now and can see what you find. This library definitely has a few quirks and hopefully can be replaced soon by a Dalamud service.
